### ISSUE TITLE
Issue with brackets menu : hide 1st line

### ISSUE THREAD

**Issue by tlemaire** [DH3ALEJANDRO/custom-work-for-brackets#1]
I removed 'z-index: 999' to style.min.css in order to see the 1st line of menu.

Brackets  1.1.0-15558 (ubuntu 64)

**Comment by tlemaire** [comment]
I did to change again and write ;z-index:10 due to worklist and it seems to work now.

**Comment by DH3ALEJANDRO** [comment]
thank you very much for the correction, in 4 days I will apply these changes. :)

**Comment by covazquez** [comment]
Where can I find the file to edit? I have the same problem. Thanks! :)

**Comment by tlemaire** [comment]
Hi.  Under linux (ubuntu) you can find in your home directory the following
file :


.config/Brackets/extensions/user/custom-work-for-brackets/style/style.min.css

change z-index:999 to z-index:10

2015-01-20 5:40 GMT+01:00 covazquez <notifications@github.com>:

**Comment by DH3ALEJANDRO** [comment]
top tab brackets : help > Show Extensions Folder
user/(name extension)
