### ISSUE TITLE
Keyboard shortcut for switching between tabs?

### ISSUE THREAD

**Issue by Neats29** [DH3ALEJANDRO/custom-work-for-brackets#10]
Thanks for this awesome extension.

Are there any keyboard shortcuts for switching between tabs rather than having to use the mouse?
Thanks!

**Comment by DH3ALEJANDRO** [comment]
thank you for the suggestion? completely rewritten extension, please wait.

**Comment by DH3ALEJANDRO** [comment]
Ctrl-Left, Ctrl-Right for version 5.0.1 :+1:
