### ISSUE TITLE
Bookmarks dont show

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#100]
Im not sure the bookmarks (blue dots left of line numbers) are cause of this plugin. I remember in older versions when i had clicked to add a couple of them and i would click bookmarks in the top-menu a list would appear. Now nothing shows???

See attached.
![screen shot 2017-11-03 at 1 52 59 pm](https://user-images.githubusercontent.com/6923008/32388520-cec207c8-c07c-11e7-9d94-19c9650e0d27.png)

**Comment by DH3ALEJANDRO** [comment]
thank you for your comment.
effectively, it is part of the plugin. I'll investigate

**Comment by schroef** [comment]
Weird thing is, on
<img width="1235" alt="screen shot 2017-11-04 at 00 56 53" src="https://user-images.githubusercontent.com/6923008/32402488-04b662e0-c0da-11e7-9d4c-6ac1fe8b7cdc.png">
 my laptop at home running the same version of brackets (1.11) and custom works 5.1.10 i do see them. Ill try to check all version numbers on the other mac Monday. I had just updated everything on that one today. Not sure why it's working here properly then.

**Comment by schroef** [comment]
I want to note that the bookmarks dont work at all again. Are those blue dots done by your addon? if so nothing happens on OSX. Using rv 5.1.8

I dont see the bookmark icon in the menu as well. Also in the bottom left there was always a icon, that doesnt show neither

![screen shot 2018-01-13 at 4 14 43 pm](https://user-images.githubusercontent.com/6923008/34909732-3bcc3eaa-f87d-11e7-84ec-8bc5d6588e45.png)

**Comment by DH3ALEJANDRO** [comment]
in the extension option do you have the markers enabled?

**Comment by schroef** [comment]
My bad, i sort of overlooked that :)

PS these are saved per computer right?

**Comment by DH3ALEJANDRO** [comment]
refers to the extension settings?

**Comment by schroef** [comment]
Not sure what you mean by that. But its quite obvious these bookmarks are saved per system.

PS that popup menu with the link, werent these clickable in earlier version. I thought i could cycle through them by clicking on them from the pop-up menu. 

I mean the small icon BR corner

**Comment by DH3ALEJANDRO** [comment]
hi: install the new version available. bug fixed

**Comment by schroef** [comment]
Im not sure it works properly. I open the bookmark and see a couple bookmarks from files. When i click it jumps through the file. But when i click another file that is open, it still jumps in the open document.

I also dont see it jump to the correct line in the file which is open?
