### ISSUE TITLE
The background color needs to change

### ISSUE THREAD

**Issue by karthie** [DH3ALEJANDRO/custom-work-for-brackets#102]
the background color is not fair for my editor and why you use this is a default color

<img width="1310" alt="screen shot 2017-12-04 at 12 33 40 pm" src="https://user-images.githubusercontent.com/16980808/33540087-66942f92-d8ef-11e7-8842-45b84f23b9ad.png">

**Comment by DH3ALEJANDRO** [comment]
uncheck the `useBlueishStyle` option
