### ISSUE TITLE
Minimap interfares with right-side hamburger drop-down menu.

### ISSUE THREAD

**Issue by MiKr13** [DH3ALEJANDRO/custom-work-for-brackets#105]
Having minimap enabled causes right-side hamburger(&#9776;) drop-down menu to become inactive as it minimap hovers above it.

![screenshot 22 _li](https://user-images.githubusercontent.com/34394719/39969314-901f50cc-56f7-11e8-918c-7b1c0d9bbb5c.jpg)

**Comment by DH3ALEJANDRO** [comment]
hi: install the new version available. bug fixed
