### ISSUE TITLE
Strange space on the right of the window

### ISSUE THREAD

**Issue by GiacomoK** [DH3ALEJANDRO/custom-work-for-brackets#106]
Hi,  
as you can see from the attachment, I have a strange black space on the right of the window.  
If I uninstall the extension this space disappears.

![schermata a 2018-06-12 13-05-17](https://user-images.githubusercontent.com/16156317/41287023-b4bd2f60-6e41-11e8-8aed-098bf04222f8.png)

**Comment by DH3ALEJANDRO** [comment]
Duplicate of #88
