### ISSUE TITLE
Icons in tabs

### ISSUE THREAD

**Issue by rafaeldev** [DH3ALEJANDRO/custom-work-for-brackets#11]
First, thanks for the extension!

Well, would like to know as it does to add icons in tabs. 

As this example:
https://raw.githubusercontent.com/DH3ALEJANDRO/custom-work-for-brackets/master/screenshoot/total%20example.gif

Thanks!

**Comment by DH3ALEJANDRO** [comment]
install this extension https://github.com/ivogabe/Brackets-Icons

**Comment by DH3ALEJANDRO** [comment]
in version 5 already it has default
