### ISSUE TITLE
Right Sidebar Overlapping Tabs Toolbar

### ISSUE THREAD

**Issue by messinmotion** [DH3ALEJANDRO/custom-work-for-brackets#12]
![screen shot 2015-07-30 at 7 19 51 am](https://cloud.githubusercontent.com/assets/5679236/8985302/69060d1c-368b-11e5-926e-c205a5afa47d.png)

**Comment by DH3ALEJANDRO** [comment]
pls brackets and OS version.

**Comment by messinmotion** [comment]
10.10.4 
Brackets 1.4

**Comment by DH3ALEJANDRO** [comment]
often it happens?

**Comment by messinmotion** [comment]
Every relaunch, disabling and enabling the plugin seems to fix it until the next launch. Do you speak spanish? I can explain better in spanish.

**Comment by DH3ALEJANDRO** [comment]
I will write a more optimal version, these days will have the update, my dialect is another (unusual) :tongue:

**Comment by DH3ALEJANDRO** [comment]
solved in version 5.0.0
