### ISSUE TITLE
Fix height for Menu and provide a scroll

### ISSUE THREAD

**Issue by Abinesh-Devadas** [DH3ALEJANDRO/custom-work-for-brackets#13]
![screenshot](https://cloud.githubusercontent.com/assets/8117653/9406623/ea0577b8-481f-11e5-95fe-7997c1b4b014.png)

Windows 7 
Brackets 10.4

remaining opened files are hidden cant access using menu (please Check screenshot)

Thank you for making this extension... its flat and neat ...

**Comment by DH3ALEJANDRO** [comment]
I am developing a new version, clean and tidy. It will be available in the next days. Thank you for using extension. :+1: 
[tnk for the report]

**Comment by Abinesh-Devadas** [comment]
Thats great ...

waiting for your new version ...

Hope will be released soon ...

**Comment by DH3ALEJANDRO** [comment]
solved in version 5 :smiley:
