### ISSUE TITLE
Keyboard Shortcuts to Hide Sidebar and Show up file list

### ISSUE THREAD

**Issue by laedri** [DH3ALEJANDRO/custom-work-for-brackets#15]
I would like to see keyboard shortcut to hide sidebar. Also another shortcut which shows up file list would be nice.

Thanks for great extension.

**Comment by DH3ALEJANDRO** [comment]
version 5.1.1
(Ctrl-Alt-H or Cmd-Alt-H > by default) Toggle Sidebar with button
(Shift-T) Show up file list (view list in active Pane)
