### ISSUE TITLE
Option to choose icons

### ISSUE THREAD

**Issue by davidbarredo** [DH3ALEJANDRO/custom-work-for-brackets#16]
The new version is awesome, thanks for it!

But now, the icons in the tabs don't match the icons in the sidebar (https://github.com/ivogabe/Brackets-Icons)

Maybe an option to choose which icons we want to show would be great.

**Comment by DH3ALEJANDRO** [comment]
I'll try :+1:

**Comment by SYNTAG** [comment]
Yes, please do this!

**Comment by DH3ALEJANDRO** [comment]
okay okay, calm. :hand:

**Comment by JoaoPedroCarvalho** [comment]
how are you doing on this? :D

**Comment by DH3ALEJANDRO** [comment]
please wait :confused:

**Comment by DH3ALEJANDRO** [comment]
update! :smile_cat:

**Comment by davidbarredo** [comment]
Wow! great work!

:grin:

Thanks.
