### ISSUE TITLE
Can't find extension settings (and can't type the uppercase letter 'T')

### ISSUE THREAD

**Issue by wantedbug** [DH3ALEJANDRO/custom-work-for-brackets#17]
Hello!
Great updates in the last few days. :+1: 
But I've just come across a major issue.
I updated the extension to v5.0.1 but then hastily closed the settings pop-up that popped up after restarting Brackets. Now I just can't seem to find it! I don't know if I'm missing something but I just can't find it under any menu.
Now the reason why I want to find the settings is I can't seem to type the uppercase letter 'T' into any editor. I remember seeing Shift + T used as a key binding in the settings pop-up.
Thanks!
[Brackets Release 1.5 build 1.5.0-16538 (release cf9cf4698)]

**Comment by sapioit** [comment]
And I also cannot use CTRL to move through words, rather than tabs... if it would have been Alt+Ctrl+arros, it would have been way simpler and create less erros like this...

**Comment by wantedbug** [comment]
Yep, I use Ctrl + Direction keys to move through words too, but I'm hoping this key binding can be disabled or changed in the settings pop-up.

**Comment by sapioit** [comment]
Looked through the code, but didn't found anything useful... I would manually delete the bindings, if I would be able to find them...

**Comment by norhug** [comment]
Same here. Can't type uppercase letter 'T'!

**Comment by ficristo** [comment]
@DH3ALEJANDRO  Could you make the shortcuts overwriteable?
On OSX I use the Command-Left Command-Right to go at the beginning end of a line, with the new version I switch on the left-right tab: is a bit of a nightmare...

**Comment by DH3ALEJANDRO** [comment]
please update to version 5.0.2 and then report if solved.
<i>I apologize for any inconvenience and thank you for using Custom Work for Brackets!</i>

**Comment by ficristo** [comment]
Seems solved for me. Thank you for the fast update.

**Comment by norhug** [comment]
Works fine now. Thank you

**Comment by sapioit** [comment]
Thanks for the awesome update!

**Comment by DH3ALEJANDRO** [comment]
:+1:

**Comment by wantedbug** [comment]
Seems solved after the update to 5.0.2. Thanks!
One thing though - I've observed that an extension's preferences menu item is usually placed in the Edit menu and not the Navigate menu. This is nitpicking, but I thought I'd let you know.
Cheers!
