### ISSUE TITLE
Toggle toolbar issue

### ISSUE THREAD

**Issue by boatkung** [DH3ALEJANDRO/custom-work-for-brackets#18]
When I click the button to hide the toolbar, it doesn't active and it cover the hide button up.

![missing_toggle_toolbar](https://cloud.githubusercontent.com/assets/3680544/11202032/66155234-8d16-11e5-8d6d-2e09c03a4d35.png)

Thanks for create this great plugin.

**Comment by DH3ALEJANDRO** [comment]
you are using any extension that changes the Toolbar?

**Comment by boatkung** [comment]
Thanks for you advice. I try to disable some extension and it's working now.

**Comment by DH3ALEJANDRO** [comment]
:+1:

**Comment by boatkung** [comment]
It's HTML Designer for Brackets.

**Comment by joseporto** [comment]
Yes.. confirmed. HTML Designer for Brackets

**Comment by DH3ALEJANDRO** [comment]
update and comment please
