### ISSUE TITLE
Middle Click on Tab

### ISSUE THREAD

**Issue by ppietris** [DH3ALEJANDRO/custom-work-for-brackets#19]
Congrats for this great Extension!

When I middle-click an open tab, I have to aim for the X button to close it.
Is it possible to work on the whole tab.

Thank u!

**Comment by DH3ALEJANDRO** [comment]
I like, but do not quite understand. You can explain in more detail

**Comment by ppietris** [comment]
Sorry. I would like to know if you can close the tab, by middle-clicking upon the tab.

![untitled-1](https://cloud.githubusercontent.com/assets/7735320/11466021/c4b1aab0-9746-11e5-8883-ef7ee4647b6c.jpg)

**Comment by DH3ALEJANDRO** [comment]
next version. :octocat:

**Comment by ppietris** [comment]
Thank u!

**Comment by DH3ALEJANDRO** [comment]
ok, :+1: please update.
<i>Sorry for taking so long to respond.</i>
