### ISSUE TITLE
Icons not appearing.

### ISSUE THREAD

**Issue by Athax** [DH3ALEJANDRO/custom-work-for-brackets#2]
You promised me icons, I don't have any!

**Comment by DH3ALEJANDRO** [comment]
can you be more specific please?

**Comment by thco** [comment]
@Athax you will get icons displayed if you install icons plugin... That's simple :)

**Comment by Athax** [comment]
Hehe it was qoute, tried to ask in a funny way. It's beacuse in your gif sample pictures there's icons on your tap how do i achive them?

**Comment by Athax** [comment]
Found the plugin thanks @thco

**Comment by DH3ALEJANDRO** [comment]
I me installed this : https://github.com/ivogabe/Brackets-Icons
