### ISSUE TITLE
Just an aesthetic request

### ISSUE THREAD

**Issue by djap96** [DH3ALEJANDRO/custom-work-for-brackets#20]
I't could be be silly for some people and irrelevant..
I think the flat icons for html and css are pretty stunning, but the dot-circle-o,svg need to be changed. Is a little bit uggly.
There's no doubt that this extension is freaking awesome.

**Comment by DH3ALEJANDRO** [comment]
click on menu > 'Help / Show Extensions Folder' 
`user/custom-work-for-brackets/sys/evr/dot-circle-o.svg` > replace the contents of the file with the code of your image svg
<i>Sorry for taking so long to respond.</i>

**Comment by djap96** [comment]
Thank you man, I apreciate that
