### ISSUE TITLE
Aesthetic request

### ISSUE THREAD

**Issue by Bassforce86** [DH3ALEJANDRO/custom-work-for-brackets#21]
Hi, It's only a very small thing, Would it be possible to either change the height of the toolbar or the height of the sidebar header so that they match?

![brackets extension issue](https://cloud.githubusercontent.com/assets/8835015/11777239/f7219d26-a244-11e5-90c9-ebfe26290e22.png)

**Comment by DH3ALEJANDRO** [comment]
ok, please update.
<i>Sorry for taking so long to respond.</i>

**Comment by Bassforce86** [comment]
Still mis-aligned, but I actually think this may be theme related sorry, I forgot to mention I use the Brackets UI Theming, The theme I Use is Monokai Dark Juice if that helps at all.

I don't think this is an issue with Tabs so my apologies!

**Comment by Bassforce86** [comment]
It was a Theme issue, sorry! If any one else needs this fixing its only a case of changing the padding.

locate your theme's theme.css.

In windows (I know, i know I don't like it much either but work requires it...) file path is:
C:/Users/*WINDOWS USER NAME*/AppData/Roaming/Brackets/extensions/user/*THEME NAME*/theme.css 

For the theme I am using (Monokai Dark Soda) line 269 project-files-header {
//Leave everything as is except padding.
- padding:12px 0 5px 12px;
+padding: 5px 0 3px 12px;
}

And that's it. Sorry if you spent to much time looking into this, Not sure why I hadn't considered it being a theme issue!

**Comment by DH3ALEJANDRO** [comment]
ok ok :sleeping:
