### ISSUE TITLE
The color of a tab

### ISSUE THREAD

**Issue by mrcompl** [DH3ALEJANDRO/custom-work-for-brackets#22]
Hi. I'm new here :)
I would like to know how to change the color of a tab, because I don't like current dark red :/
http://i.imgur.com/62pXbw1.png
I've seen somewhere the version with blue border-bottom
Oh, like that: https://camo.githubusercontent.com/997bed7f437100df4bcf6f787e587f52c0980207/687474703a2f2f6935372e74696e797069632e636f6d2f366f323434312e706e67
Thanks in advance.
Sorry if this topic doesn't fit here. I've just signed up and don't know "how and where" ;)

**Comment by DH3ALEJANDRO** [comment]
> Yes that is fine. is here :+1: 

It is an outdated theme, I will find a solution

**Comment by Bassforce86** [comment]
I've modified the cap.css file to display with the blue underline and dark grey background, like this? 
![brackets colour tabs change](https://cloud.githubusercontent.com/assets/8835015/12156628/f057143a-b4c3-11e5-8bdb-8c791eeaebf9.PNG)

Is this what you were after? I've highlighted the lines I have changed, please check with extension author before making these changes, in case there are other places this needs updating!

cap.css file location (windows): C:/Users/**windows user name**/AppData/Roaming/Brackets/extensions/user/custom-work-for-brackets/sys/**cap.css**

Hope this helps!
