### ISSUE TITLE
what is OSB＋ May ＋ Tab means

### ISSUE THREAD

**Issue by evolutionjay** [DH3ALEJANDRO/custom-work-for-brackets#23]
OSB＋ May ＋ Tab
Yes i knew OSB is command in mac， but what is this " May"?

**Comment by DH3ALEJANDRO** [comment]
May is Shift key

**Comment by LukaszGrela** [comment]
so where this May comes from?

**Comment by DH3ALEJANDRO** [comment]
I'm confused, somewhere I must have been wrong. I will change it (next version) :smile_cat:

**Comment by DH3ALEJANDRO** [comment]
v5.0.5 :expressionless:
