### ISSUE TITLE
I'm not seeing any icon on the toolbar

### ISSUE THREAD

**Issue by dnagyelek** [DH3ALEJANDRO/custom-work-for-brackets#25]
Can I disable that?

There is a spaced hidden icon, and I don't really need that.
![capture](https://cloud.githubusercontent.com/assets/15093785/12143522/f4635d7a-b489-11e5-8653-836d66f1d740.PNG)

Bests,
David

**Comment by DH3ALEJANDRO** [comment]
:+1:
