### ISSUE TITLE
tab width

### ISSUE THREAD

**Issue by asd-j** [DH3ALEJANDRO/custom-work-for-brackets#26]
Can I change tab width?

![width](https://cloud.githubusercontent.com/assets/16645746/12230727/9c24fee2-b895-11e5-9583-42154b5f7181.png)
It is wide.

Thanks this extension! and sorry for my poor English.

**Comment by boatkung** [comment]
I agree, It's too wide when open, just single or 2 tabs.
I'm avoiding to update my another PC because like this.
I prefer scrollable tabs.

**Comment by DH3ALEJANDRO** [comment]
please wait :frowning:

**Comment by DH3ALEJANDRO** [comment]
update v5.0.7 :smile:

**Comment by asd-j** [comment]
Thank you for your rapid response!:smile:
