### ISSUE TITLE
Tab missing

### ISSUE THREAD

**Issue by boatkung** [DH3ALEJANDRO/custom-work-for-brackets#27]
When I split window and move tabs between window.

![tab_missing](https://cloud.githubusercontent.com/assets/3680544/12255060/36d3e426-b922-11e5-90e5-67a8b90a7c2f.gif)

**Comment by DH3ALEJANDRO** [comment]
:confused: wait...

**Comment by DH3ALEJANDRO** [comment]
already solved :grinning:v5.0.8

**Comment by boatkung** [comment]
Tabs are working now, but I see something weird about icon instead. LOL

![icon_weird](https://cloud.githubusercontent.com/assets/3680544/12271770/6be97d48-b98f-11e5-932b-b67e56ba6e4a.png)

But I don't mind this icon issue.
Thanks for quickly update extension. :smile:
