### ISSUE TITLE
Can I hide/disable the Working Files tab?

### ISSUE THREAD

**Issue by dnagyelek** [DH3ALEJANDRO/custom-work-for-brackets#28]
I know that is not an issue, but can I do that and how?

Thank you,
David

**Comment by DH3ALEJANDRO** [comment]
you can indicate a picture

**Comment by dnagyelek** [comment]
Sorry, I've forgot that :)
![capture](https://cloud.githubusercontent.com/assets/15093785/12262706/1ac883c6-b932-11e5-8faa-918f09017d8e.PNG)

Second thing, I had to remove also the Brackets Icons because they've messed up the Working Files, duplicating the icons.

**Comment by DH3ALEJANDRO** [comment]
v5.0.8 <i>find option in Navigate Menu Brackets</i>

**Comment by dnagyelek** [comment]
Perfect, thank you
