### ISSUE TITLE
File type icon issue

### ISSUE THREAD

**Issue by LukeMcGurdy** [DH3ALEJANDRO/custom-work-for-brackets#29]
I'm seeing the below pic as of the latest update to your excellent extension. Note that file type icons are tripling up for each file. My assumption here is that it's a problem with custom - tabs working and not another extension like https://github.com/ivogabe/Brackets-Icons 

![example](https://cloud.githubusercontent.com/assets/7559210/12261488/50007d8c-b919-11e5-9c6f-3e6f5233d138.jpg)

**Comment by DH3ALEJANDRO** [comment]
:confused: <i>it's just a feature to take advantage of icons</i>

**Comment by LukeMcGurdy** [comment]
Perhaps I'm misunderstanding. But please take another look at the image above. Why would I want to see 3 icons per file? 

FYI, I've just disabled the extension I mentioned before (should have done this previously) and the issue doesn't arise.

**Comment by DH3ALEJANDRO** [comment]
v5.0.8[fix multiple  bugs]<br>
is solved? :grin:

**Comment by LukeMcGurdy** [comment]
Almost! One down, one to go ;) 

The icons on the left are generated by the Brackets Icons extension and the icons on the right are generated by your extension.

![untitled-1](https://cloud.githubusercontent.com/assets/7559210/12271104/6c69831e-b951-11e5-9e84-9afb7fb8aae8.jpg)

**Comment by DH3ALEJANDRO** [comment]
preferences in Brackets Navigate Menu > uncheck 'addiconprovider' :wink:

**Comment by LukeMcGurdy** [comment]
You, sir, are a genius! Thanks. 
: )

**Comment by Dehehet** [comment]
Thanks! I have same issue too.

**Comment by Daryll0222** [comment]
how to go Preferences?

**Comment by DH3ALEJANDRO** [comment]
@Daryll0222 

![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)

*for more*
https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences
