### ISSUE TITLE
Settings UI

### ISSUE THREAD

**Issue by CupOfTea696** [DH3ALEJANDRO/custom-work-for-brackets#31]
It'd be nice if the settings UI that pops up every update would be accessible through a menu. It also looks very cluttered so a better view would be great too!

**Comment by DH3ALEJANDRO** [comment]
ok, ok :+1: <i>(for menu : Navigate Menu (top editor) > 'Custom Work for Brackets Preferences')</i>

**Comment by DH3ALEJANDRO** [comment]
v5.1.0 :arrow_down:
