### ISSUE TITLE
Double icons with single icon extension installed

### ISSUE THREAD

**Issue by dmxt** [DH3ALEJANDRO/custom-work-for-brackets#32]
I use [Brackets Icons by Ivo Gabe de Wolff](https://github.com/ivogabe/Brackets-Icons) and after installing this Tabs extension, I have a weird bug of unwanted double icons.

How do I solve this problem? It doesn't look alike as Tabs extension official screenshot. 

Screenshot:
![Brackets](http://i.imgur.com/Ff7ZWBx.png)

**Comment by DH3ALEJANDRO** [comment]
[Here](https://github.com/DH3ALEJANDRO/custom-work-for-brackets/issues/29#issuecomment-170993607)
