### ISSUE TITLE
Missing eyelashes

### ISSUE THREAD

**Issue by HaruIjima-kun** [DH3ALEJANDRO/custom-work-for-brackets#33]
Hello there!

I found a bug a bit annoying, I have the brackets divided into two, and when passing a tab from one side to the other, I step away and none appears in the bar, the alleged bar I have three tabs but none appears, I have to restart the brackets to display it.

I hope it is resolved soon!

![screen](https://cloud.githubusercontent.com/assets/11773810/12373607/4a0f2324-bc7f-11e5-80a4-2fc24056a501.png)

**Comment by DH3ALEJANDRO** [comment]
ok ,please [gif]...

**Comment by HaruIjima-kun** [comment]
If restarting the brackets become visible ...

![gif complete bug](https://cloud.githubusercontent.com/assets/11773810/12380888/96f2d6c8-bd7d-11e5-84d6-1e1340cfb8d9.gif)

**Comment by aliko** [comment]
Yea same issue, I always use split view, but sometimes it isn't easy to find out on which file you working when you can't see the file title at the top bar!

**Comment by DH3ALEJANDRO** [comment]
I'm working on it.

**Comment by HaruIjima-kun** [comment]
Thank you ;)

**Comment by DH3ALEJANDRO** [comment]
Please Update to v5.1.0 :octocat: :smiley:

**Comment by aliko** [comment]
Thank you DH3ALEJANDRO! :+1:

**Comment by HaruIjima-kun** [comment]
Thank you! :+1:
