### ISSUE TITLE
How can i disable the icons

### ISSUE THREAD

**Issue by JJzcru** [DH3ALEJANDRO/custom-work-for-brackets#34]

**Comment by DH3ALEJANDRO** [comment]
[Here](https://github.com/DH3ALEJANDRO/custom-work-for-brackets/issues/29#issuecomment-170993607)

**Comment by pjb493** [comment]
I also want to disable the icons, but not just the extra sidebar ones, the ones on the tabs as well. I want the tabs to use the icons from a separate icon set as they did in version 4.0.1
Can you do this please?

**Comment by st-stephen2** [comment]
For me, the icons make Brackets too colorful and take up space that could be used for file names. If I could disable icons on the tabs as well as the file tree, that would be extremely cool.

**Comment by pjb493** [comment]
Ideally just put in an option to revert back to the system used in 4.0.1 where the tabs bar was based purely on the look of the file tree, i.e. No icons unless the user had installed a separate icon set, only then would there be icons on the tabs.

**Comment by DH3ALEJANDRO** [comment]
update `"custom.work.useIconsOfCustomWork": false`
