### ISSUE TITLE
Bug in split view

### ISSUE THREAD

**Issue by aliko** [DH3ALEJANDRO/custom-work-for-brackets#35]
in the split view I don't see the close button! Also, when there are too many tabs, I can't slide to close the last one. It became really buggy since the new update!

**Comment by DH3ALEJANDRO** [comment]
please wait...:confused:

**Comment by DH3ALEJANDRO** [comment]
Please Update and Report...

**Comment by aliko** [comment]
Thank you very much DH3ALEJANDRO! The new update fixed all the issues! Thanks a million matey! :+1:
