### ISSUE TITLE
Disable hover in file titles

### ISSUE THREAD

**Issue by GuiAlmeida** [DH3ALEJANDRO/custom-work-for-brackets#37]
<img width="1027" alt="captura de tela 2016-01-20 as 11 59 43" src="https://cloud.githubusercontent.com/assets/5199435/12450889/5ca729e6-bf6d-11e5-9487-f10fea5d3d55.png">

**Comment by DH3ALEJANDRO** [comment]
Menu Brackets / Navigate / preferences / uncheck tooltip
