### ISSUE TITLE
hoverSidebar not working on Brackets 1.6 ( T-CW version 5.0.9 )

### ISSUE THREAD

**Issue by nikitul** [DH3ALEJANDRO/custom-work-for-brackets#38]
hoverSidebar not working on Brackets 1.6 ( T-CW version 5.0.9 ).
but is working on Brackets 1.5.

Great Job.
Thanks

**Comment by DH3ALEJANDRO** [comment]
ok, something went wrong

**Comment by nikitul** [comment]
After I read issue https://github.com/DH3ALEJANDRO/custom-work-for-brackets/issues/36 , I edited brackets.json
"custom.work.geticonprovider": false,

and everything is ok now.
I don't know why didn't worked from the start.
