### ISSUE TITLE
Having separate tab list when splitting

### ISSUE THREAD

**Issue by warpdesign** [DH3ALEJANDRO/custom-work-for-brackets#4]
I wish the extension would correctly handle split mode.

When in split mode it seems the extension only shows the files opened on the first (left/top) view, and it takes the whole width of the screen.

This is really confusing, and you don't have access to your files opened on the second view.

![brackets](https://cloud.githubusercontent.com/assets/199648/6145432/11c8d288-b1e2-11e4-9ab0-db71adb6143e.png)

**Comment by DH3ALEJANDRO** [comment]
I'm working on an improvement for convenient use of the total area, is likely to end in 2 or 3 days.

**Comment by warpdesign** [comment]
Great!
