### ISSUE TITLE
Is supporting tilt-scroll/side scroll in tabs bar possible?

### ISSUE THREAD

**Issue by grvrai** [DH3ALEJANDRO/custom-work-for-brackets#40]
I use the plugin on both windows and mac. I have a tile scroll mouse on windows and magic mouse for mac. The vertical scroll on the tabs bar seems a bit unnatural. Will it be possible to have a setting to change this option?

**Comment by DH3ALEJANDRO** [comment]
screenshot please [gif]

**Comment by grvrai** [comment]
Not as important.
