### ISSUE TITLE
New tabs stop being created after dot-files are opened

### ISSUE THREAD

**Issue by DigitalFeonix** [DH3ALEJANDRO/custom-work-for-brackets#41]
I found that new tabs cease being created after opening dot-files without an extension; such as .editorconfig or .htaccess, but NOT .brackets.json.

As long as these files are in the working files double-click opening, or opening and saving, no longer adds new files to the tabs list even though they are in the working files list. And once closed, any missing tabs will reappear.

Also moving these special files within the working list in the sidebar show that it and all files below it to not have tabs.

Brackets v1.6 and Custom Working Tabs v 5.0.9

**Comment by DH3ALEJANDRO** [comment]
screenshot please [gif]

**Comment by DigitalFeonix** [comment]
With a dot-file in the working list. It and the files after it don't have tabs. Nor does the listView icon show

![1](https://cloud.githubusercontent.com/assets/197201/12535251/d9699e98-c231-11e5-85b0-561e1bf0abf6.png)

Close the dot-file from the list and the tabs are restored.

![2](https://cloud.githubusercontent.com/assets/197201/12535252/dbe1f0d0-c231-11e5-8fbe-591df63721af.png)

**Comment by DH3ALEJANDRO** [comment]
please Update (v5.1.0) and scribe a report :cat:

**Comment by DigitalFeonix** [comment]
Working as expected.

![screen](https://cloud.githubusercontent.com/assets/197201/12758066/a4135198-c98f-11e5-97e6-2733214b16ef.png)

Brackets v1.6 and Custom Working Tabs v 5.1.0
