### ISSUE TITLE
Completely disable new tab icons

### ISSUE THREAD

**Issue by pjb493** [DH3ALEJANDRO/custom-work-for-brackets#42]
I want to disable the icons, but not just the extra sidebar ones, the ones on the tabs as well. I want the tabs to use the icons from a separate icon set as they did in version 4.0.1
Can you do this please?

**Comment by DH3ALEJANDRO** [comment]
Please wait

**Comment by DH3ALEJANDRO** [comment]
update `"custom.work.useIconsOfCustomWork": false`
