### ISSUE TITLE
Suggestion: Aligning file list

### ISSUE THREAD

**Issue by dumb** [DH3ALEJANDRO/custom-work-for-brackets#43]
I'd like to suggest a small css change that will clean up the file list.

As it is now, the filetype icons are all different widths, which causes the filenames to jut all over the place. Here's a sample of how it looks now:

![before](https://cloud.githubusercontent.com/assets/857046/12686465/c70efea4-c697-11e5-88bb-13705cd049ed.png)

With a bit of css they can be straightened out to look much cleaner, like this:

![after](https://cloud.githubusercontent.com/assets/857046/12686454/bb057584-c697-11e5-9766-59ef10c45a73.png)

I edited the iconpackage.css file and added a couple of lines:

	.cw-box-list-view .file-icon-bar,
	.cw-tabbar .file-icon-bar,
	.jstree-brackets .file-icon-bar,
	.open-files-container .file-icon-bar {
		vertical-align: text-bottom;
		padding-right: 5px;
		font-size: 15px;
		text-align: center; /* added */
		width: 20px;  /* added */
	}

_(on Mac the file is found at ~/Library/Application\ Support/Brackets/extensions/user/custom-work-for-brackets/sys/iconpackage.css)_

I'm not sure if there's a more elegant way to do this, but so far it seems to work well for me. Ymmv. Thanks for this great extension!

**Comment by DH3ALEJANDRO** [comment]
perfect! That's great! I include it :smile:

**Comment by DH3ALEJANDRO** [comment]
update 5.1.0 :octocat:
