### ISSUE TITLE
Disable Working Files in the left panel

### ISSUE THREAD

**Issue by henriquebach** [DH3ALEJANDRO/custom-work-for-brackets#45]
i loved the tabs, great job, but what is annoying me is the working files in the left, because they are useless now. how can i disable it?

**Comment by leosilvano** [comment]
Debug > Open Preferences File

Find "custom.work.workingFilesSidebar" and change it to false

**Comment by henriquebach** [comment]
thank you man

**Comment by DH3ALEJANDRO** [comment]
:+1:
