### ISSUE TITLE
Add icon for .editorconfig files

### ISSUE THREAD

**Issue by josegoncalveswho** [DH3ALEJANDRO/custom-work-for-brackets#46]
currently, on my usual setup, I'm missing an icon for **.editorconfig** files. Maybe something similar to **.project** icon would be fine.

**Comment by DH3ALEJANDRO** [comment]
ok :+1:

**Comment by DH3ALEJANDRO** [comment]
update

**Comment by josegoncalveswho** [comment]
Cool, it's a good thing that we are doing our best to support Brackets. Thanks
