### ISSUE TITLE
Display full name with multiple open files

### ISSUE THREAD

**Issue by loorlab** [DH3ALEJANDRO/custom-work-for-brackets#47]
Hi Friend, how to change display full name ?

After Update 5.1

![brackets](https://cloud.githubusercontent.com/assets/3799679/12871329/9cc05a38-cd42-11e5-8aa5-ab14f29fd289.png)

Before Update 5.1

https://cloud.githubusercontent.com/assets/3680544/11202032/66155234-8d16-11e5-8d6d-2e09c03a4d35.png

Help Us !

Thanks

**Comment by DH3ALEJANDRO** [comment]
update `"custom.work.scrollwheel": true`

**Comment by loorlab** [comment]
Alejandro, thanks 

Really nice !

![bu](https://cloud.githubusercontent.com/assets/3799679/16063397/9fec41e6-325e-11e6-9775-88fef5db2776.png)
