### ISSUE TITLE
Hover sidebar is spotty, and the sidebar state resets when Brackets is restarted

### ISSUE THREAD

**Issue by mrapino** [DH3ALEJANDRO/custom-work-for-brackets#49]
Hello, 

There are two items that are glitchy in my opinion. 

First: for some reason, the hover state of the sidebar stops working every so often.  There is no rhyme or reason for the issue, so I can't really go into more detail than that. 

Second: I like the hover state of the sidebar, however, I'd like the choice to keep the sidebar closed, and continue using hover without having to set it up every time I open Brackets.  The way it is now, the sidebar is open when I go into Brackets, and I have to collapse the sidebar every time.  I'd like the sidebar to remain collapsed. 

Thanks!

**Comment by DH3ALEJANDRO** [comment]
remove addons `no-Distraction mode`. important!
