### ISSUE TITLE
In split mode, open files from the tab to the right does not displayed in the menu

### ISSUE THREAD

**Issue by true0r** [DH3ALEJANDRO/custom-work-for-brackets#5]
Hi, sorry for my language, i only trained. See screenshot for v3.01.
![screenshot](https://cloud.githubusercontent.com/assets/8409258/6333126/39992f14-bb93-11e4-88be-7f01fb376656.PNG)
It would be great if .pane-header was hidden in normal mode
![screenshot](https://cloud.githubusercontent.com/assets/8409258/6333158/9074323e-bb93-11e4-8a0f-e3406a49169e.PNG)

Thank you

**Comment by DH3ALEJANDRO** [comment]
there! please update :)

**Comment by true0r** [comment]
very good) thanks!
still a problem, a scrollbar top closes the menu
![screenshot](https://cloud.githubusercontent.com/assets/8409258/6339473/fd4a854a-bbbe-11e4-82d7-4567f05a00b6.PNG)

**Comment by true0r** [comment]
change in #workfile-avril {raight: 12px}

**Comment by true0r** [comment]
see your a theme (xcode) where scrollbar width:6px
is the best option as more space for coding

**Comment by Equinoxdawg** [comment]
@DH3ALEJANDRO in fixing this I think you broke tabs working in split view. I can't get tabs to become responsive when the split view is open. Seems to only be not working when it's the horizontal split view.

![](http://i.imgur.com/IjviqcE.png)

**Comment by DH3ALEJANDRO** [comment]
[sorry for the delay] > I've probably solved, please report it. >> ;)

**Comment by Equinoxdawg** [comment]
Confirming it's fixed. 

Another thing, did the cursor ever change when hovering over the tab (and/or the X)?

If yes; that's now gone. If no; ignore this, I'm imagining things.

**Comment by DH3ALEJANDRO** [comment]
please screenShot > Equinoxdawg
