### ISSUE TITLE
The plug is switched off after a reboot Brackets

### ISSUE THREAD

**Issue by edDimensi** [DH3ALEJANDRO/custom-work-for-brackets#52]
![tabs-not-work](https://cloud.githubusercontent.com/assets/11390039/14227488/c24224bc-f907-11e5-8dde-8ba2247628b2.gif)
Only after Re-Enable plugin start work. Sorry for english.

**Comment by DH3ALEJANDRO** [comment]
update now

**Comment by MaciejHanajczyk** [comment]
I've just downloaded a fresh version of it and it is still getting disabled after Brackets restart.

**Comment by DH3ALEJANDRO** [comment]
:worried: Please share `.gif` file

**Comment by bborn787** [comment]
The gif file by @edDimensi I think that is enough to describe the issue.

Actually I got this issue after enable the Live Preview Multibrowser.
You can get more information about "Live Preview Multibrowser" here:
https://github.com/adobe/brackets/wiki/Live-Preview-Multibrowser

Also, I got some error notification
`Uncaught Error: Module name "text!sys/NoDistractions.js" has not been loaded yet for context: custom-work-for-brackets
http://requirejs.org/docs/errors.html#notloaded`

**Comment by DH3ALEJANDRO** [comment]
Please verify now
