### ISSUE TITLE
Preferences Explanations Pls

### ISSUE THREAD

**Issue by syberknight** [DH3ALEJANDRO/custom-work-for-brackets#55]
forgive me, but i'm a Brackets noob. 

i installed your extension but find myself confused by a few things...

`"custom.work.addiconprovider": true,`
i'm assuming this is to choose the kind/style/look of the icons in the file list next to each file. but i can't figure out how to change it nor what to change it to.

`"custom.work.hoverSidebar": true,`
i can't figure out what this does. whether i have it set to "true" or "false" i see no changes happen & can't find an explanation for it.

`"custom.work.listView": true,`
i can't figure out what this does & haven't found any explanations for it. not seeing any changes when i toggle it.

`"custom.work.toggleToolbar": true,`
i'm not seeing any changes when i toggle this on/off either. what does it do? doesn't seem to do the obvious.

`"custom.work.tooltip": true,`
assuming this shows tooltips somewhere. i thought Brackets already did that tho.

`"custom.work.workingFilesSidebar": true,`
discovered this shows/hides that panel above the file listing that shows which files are "open". i turned to "false" now that there are these wonderful tabs.

`"custom.work.zIndex": true,`
i know what a z-index does in CSS but i don't know how that relates to this setting.

after researching these, i discovered the option under the Navigate menu to open up a GUI for these preferences **_(minus the toggleToolbar option)_**. but above that section in this window, you have listed some keyboard shortcuts... 
WTH is the "**OSB**" key???!??!
i couldn't find any reference for it by google'ing it.

thanks for your time & efforts.

**Comment by DH3ALEJANDRO** [comment]
Please verify now

**Comment by wireinet** [comment]
hello! where you can find this options? i trying to find configuration whats appearing with first launch! i check to move sidebar buttons to the bottom - but find thats inconvenient! and cant go back!

**Comment by JosephCaillet** [comment]
@wireinet I don't know if you can open again the configuration window, but you can edit preferences manually in brackets' configuration file. (You can open it in the debug menu of brackets)

**Comment by DH3ALEJANDRO** [comment]
![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)
