### ISSUE TITLE
Color of items in the list of files not contrasting colors

### ISSUE THREAD

**Issue by loorlab** [DH3ALEJANDRO/custom-work-for-brackets#57]
Hi again, In the attached picture looks like the list you can not read the file name
![bu](https://cloud.githubusercontent.com/assets/3799679/16063553/a4e5fc36-325f-11e6-8b6b-618322901c42.png)

Thks !

**Comment by wrcode** [comment]
I have the same problem i think it's bcz of bad linking the stylesheet

**Comment by syberknight** [comment]
and the Tab bar is now BLUE! any ideas how to change that back?

**Comment by CortesHub** [comment]
Hi, I have a quick fix ! 
open simple.css 
(C:\Users\USERNAME\AppData\Roaming\Brackets\extensions\user\custom-work-for-brackets\sys) and replace with this css : http://pastebin.com/e71hNVAQ 
(1 month),

![sans titre](https://cloud.githubusercontent.com/assets/14122132/16081807/6cce2980-330f-11e6-835d-f03935ac5bf1.png)

**Comment by DH3ALEJANDRO** [comment]
ok, thanks @CortesHub. I am working on it

**Comment by syberknight** [comment]
@CortesHub  THANK YOU!!!

**Comment by HaruIjima-kun** [comment]
Thank You @CortesHub and @DH3ALEJANDRO! I like this extension so much! nice work!

**Comment by kemie** [comment]
The path on Mac: ~/Library/Application Support/Brackets/extensions/user/custom-work-for-brackets/sys

**Comment by loorlab** [comment]
Alejandro, we update the plugin and it's okay, thank you.

![bb](https://cloud.githubusercontent.com/assets/3799679/16292138/2bb47fba-38d4-11e6-984d-1ed44c3a2233.png)
