### ISSUE TITLE
Extension Error

### ISSUE THREAD

**Issue by centrual** [DH3ALEJANDRO/custom-work-for-brackets#58]
Hey,

Extension doesn't displaying anymore after last update.
I tested
1) Delete & reinstall from brackets extension manager. Not worked
2) Delete & reinstall from url : https://raw.githubusercontent.com/DH3ALEJANDRO/custom-work-for-brackets/master/install/custom-work-for-brackets.zip ( It's worked, but it displays update button in the extensions ), i pressed update button and restarted brackets, it not worked 1 more time.

Thanks

**Comment by DH3ALEJANDRO** [comment]
:worried: version

**Comment by centrual** [comment]
Working version: 3.0.0
Not working version: 5.1.1

After update( 5.1.1 ): https://i1.someimage.com/1Qtk7ad.png
After install from extension manager: 
![image](https://cloud.githubusercontent.com/assets/2001424/16172690/285a28d8-3596-11e6-9d09-f742d1a3a548.png)
After install from extension manager - developer console messages: 
![image](https://cloud.githubusercontent.com/assets/2001424/16172702/50dcb71c-3596-11e6-84fa-1a5fd83eb6e0.png)
![image](https://cloud.githubusercontent.com/assets/2001424/16172703/5972ca74-3596-11e6-9521-9e25442ecc6f.png)
Install from url: 
![image](https://cloud.githubusercontent.com/assets/2001424/16172710/7713289e-3596-11e6-97f7-b738b1bac503.png)

All of my extensions:
![image](https://cloud.githubusercontent.com/assets/2001424/16172715/80a66b82-3596-11e6-9e99-e38d334549d3.png)

![image](https://cloud.githubusercontent.com/assets/2001424/16172717/88ae0970-3596-11e6-9dc0-d119cf5c4153.png)

![image](https://cloud.githubusercontent.com/assets/2001424/16172722/90221782-3596-11e6-80e7-8b0d699bf5e5.png)

![image](https://cloud.githubusercontent.com/assets/2001424/16172723/957100f4-3596-11e6-865a-e561466c3b0e.png)

Full Developer Console Dump after install 5.1.1:

```
 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/utils/DeprecationWarning.js:90 PreferencesManager.convertPreferences() has been deprecated. Please upgrade to the current Preferences system (https://github.com/adobe/brackets/wiki/Preferences-System#conversion-from-the-pre-36-preferences-system).
    at Object.convertPreferences (/preferences/PreferencesManager.js:325:28)
    at Object.eval (/utils/Resizer.js:560:24)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
3/command/Menus.js:820 Error setting menu item shortcut: 1
/utils/DeprecationWarning.js:90 Use WorkspaceManager.recomputeLayout() instead of EditorManager.resizeEditor().
    at Object.resizeEditor (/editor/EditorManager.js:529:28)
    at Object.<anonymous> (file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/themesforbrackets/main.js:93:23)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:28280)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:27724)
    at Object.e.(anonymous function) [as resolve] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:28704)
    at HTMLLinkElement.eval (/utils/ExtensionUtils.js:209:36)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.fireWith [as resolveWith] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:27724)
/utils/ExtensionLoader.js:220 [Extension] failed to load C:/Users/Oğuz/AppData/Roaming/Brackets/extensions/user/custom-work-for-brackets - Error: Module name "thirdparty/mustache/mustache" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
/utils/ExtensionLoader.js:224 Error: Module name "thirdparty/mustache/mustache" has not been loaded yet for context: _
http://requirejs.org/docs/errors.html#notloaded
    at makeError (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:166:17)
    at Object.localRequire [as getModule] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1400:44)
    at Object.<anonymous> (file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/custom-work-for-brackets/sys/preferences.js:1:1161)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1658:33)
    at Object.Module.check (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:869:55)
    at Object.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1121:34)
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:132:23
    at file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1164:21
    at each (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:57:31)
    at Object.Module.emit (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/requirejs/require.js:1163:17)
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at new ProjectObserver (file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/dnbard.projects/services/projectObserver.js:7:20)
    at Object.<anonymous> (file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/dnbard.projects/main.js:7:27)
    at Object.context.execCb (file:///C:/Program%20Files%20(x86)
file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js Failed to load resource
http://online-dnbard.rhcloud.com/tick/542ba89acfe5e6c4c60000e2 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
/utils/DeprecationWarning.js:90 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:469:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:405)
    at registerListeners (file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/brackets-sql-connector/main.js:1265:25)
    at file:///C:/Users/O%C4%9Fuz/AppData/Roaming/Brackets/extensions/user/brackets-sql-connector/main.js:1618:3
    at _callHandler (/utils/AppInit.js:93:13)
    at Object._dispatchReady (/utils/AppInit.js:113:13)
    at Object.eval (/brackets.js:279:33)
    at j (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:26911)
    at Object.k.add [as done] (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:556:27220)
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-T to io.emmet.matching_pair. It is already assigned to brackets-nodejs-integration.start-current-test
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-J to io.emmet.split_join_tag. It is already assigned to brackets-nodejs-integration.go-to-require
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp
/command/KeyBindingManager.js:749 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown
/command/Menus.js:820 Error setting menu item shortcut: 1
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] --> ComQuitPacket
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] { command: 1 }
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] 
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] <-- HandshakeInitializationPacket
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] { protocolVersion: 10,
  serverVersion: '5.6.25',
  threadId: 1023,
  scrambleBuff1: <Buffer 7d 43 75 43 30 63 23 24>,
  filler1: <Buffer 00>,
  serverCapabilities1: 63487,
  serverLanguage: 8,
  serverStatus: 2,
  serverCapabilities2: 32895,
  scrambleLength: 21,
  filler2: <Buffer 00 00 00 00 00 00 00 00 00 00>,
  scrambleBuff2: <Buffer 2a 46 62 39 35 3e 77 60 58 78 74 5c>,
  filler3: <Buffer 00>,
  pluginData: 'mysql_native_password',
  protocol41: true }
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] 
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] --> ClientAuthenticationPacket
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] { clientFlags: 521167,
  maxPacketSize: 0,
  charsetNumber: 33,
  filler: undefined,
  user: 'root',
  scrambleBuff: <Buffer >,
  database: 'gamergambling',
  protocol41: true }
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] 
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] <-- OkPacket
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] { fieldCount: 0,
  affectedRows: 0,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '',
  protocol41: true,
  changedRows: 0 }
extensions/default/DebugCommands/NodeDebugUtils.js:117 [node-log 8:54:17 PM] 
```

**Comment by centrual** [comment]
5.1.0 tested, 5.1.0 working too.

**Comment by centrual** [comment]
I checking differences between 5.1.0 and 5.1.1

In package.json
5.1.0    => "files":["package.json","main.js"] 
            => "engines": { "brackets": ">=0.44.0" },

5.1.1    => DELETED
            => "engines": { "brackets": ">1.5.0" },
            => Files added

**Comment by DH3ALEJANDRO** [comment]
<i>please version brackets</i>
> try...
download package > [direct URL](https://s3.amazonaws.com/extend.brackets/custom-work-for-brackets/custom-work-for-brackets-5.1.1.zip])
...decompres
find file `~/sys/preferences.js` and edit > `Mustache = brackets.getModule("thirdparty/mustache/mustache")` >> (remove var)
...move the folder to the address `~/extensions/user` >> (Brackets Menu Help / Show Extensions Folder)
...comment

**Comment by centrual** [comment]
I downloaded it but my preferences.js file is uglified. So content is:

define(function(require,o,t){"use strict";function R(e,o,t,r,n){i.register(e,o,t),c.addMenuItem(o,"",r,n)}function _(e){return u.get(e)}function T(e,o,t){o!==t&&u.set(e,o)}function v(e,o,t,r){r?T(t,parseInt(e.find(o).val(),10),_(t)):T(t,e.find(o).is(":checked"),_(t))}function I(){var e=r.showModalDialogUsingTemplate(M,!0),o=e.getElement();o.find("#PREFS_showWorkingFilesSidebar").prop("checked",_(f)),o.find("#PREFS_showButtonForToolbar").prop("checked",_(g)),o.find("#PREFS_useIconsOfCustomWork").prop("checked",_(h)),o.find("#PREFS_autoHideTheTabmenu").prop("checked",_(p)),o.find("#PREFS_hoverSidebar").prop("checked",_(k)),o.find("#PREFS_tooltip").prop("checked",_(m)),o.find("#PREFS_scrollwheel").prop("checked",_(S)),o.find("#PREFS_scrollwheelStep").val(_(P)),e.done(function(e){"cancel"!==e&&"dontsave"!==e&&"ok"===e&&(v(o,"#PREFS_scrollwheelStep",P,!0),v(o,"#PREFS_showWorkingFilesSidebar",f),v(o,"#PREFS_showButtonForToolbar",g),v(o,"#PREFS_useIconsOfCustomWork",h),v(o,"#PREFS_autoHideTheTabmenu",p),v(o,"#PREFS_hoverSidebar",k),v(o,"#PREFS_tooltip",m),v(o,"#PREFS_scrollwheel",S),u.save())})}var r=brackets.getModule("widgets/Dialogs"),n=brackets.getModule("thirdparty/mustache/mustache"),s=brackets.getModule("strings"),a=brackets.getModule("command/Menus"),c=a.getMenu(a.AppMenuBar.NAVIGATE_MENU),i=brackets.getModule("command/CommandManager"),l=brackets.getModule("command/Commands"),d=brackets.getModule("preferences/PreferencesManager"),u=d.getExtensionPrefs("custom.work"),f="showWorkingFilesSidebar",g="showButtonForToolbar",h="useIconsOfCustomWork",p="autoHideTheTabmenu",k="hover.sidebar",m="tooltip",S="scrollwheel",P="scrollwheel.step",b="cw-version-in-localStorage",w=511,F=localStorage.getItem(b),E=require("text!./preferences.html"),M=n.render(E,s);R("Custom Work Preferences","PreferencesforCustomWorkforBrackets",I,a.AFTER,l.NAVIGATE_PREV_DOC_LIST_ORDER),(!F||w>parseInt(F,10))&&(localStorage.setItem(b,w),I())});

**Comment by DH3ALEJANDRO** [comment]
replace text by this
>`define(function(require,o,t){"use strict";function R(e,o,t,r,n){i.register(e,o,t),c.addMenuItem(o,"",r,n)}function _(e){return u.get(e)}function T(e,o,t){o!==t&&u.set(e,o)}function v(e,o,t,r){r?T(t,parseInt(e.find(o).val(),10),_(t)):T(t,e.find(o).is(":checked"),_(t))}function I(){var e=r.showModalDialogUsingTemplate(M,!0),o=e.getElement();o.find("#PREFS_showWorkingFilesSidebar").prop("checked",_(f)),o.find("#PREFS_showButtonForToolbar").prop("checked",_(g)),o.find("#PREFS_useIconsOfCustomWork").prop("checked",_(h)),o.find("#PREFS_autoHideTheTabmenu").prop("checked",_(p)),o.find("#PREFS_hoverSidebar").prop("checked",_(k)),o.find("#PREFS_tooltip").prop("checked",_(m)),o.find("#PREFS_scrollwheel").prop("checked",_(S)),o.find("#PREFS_scrollwheelStep").val(_(P)),e.done(function(e){"cancel"!==e&&"dontsave"!==e&&"ok"===e&&(v(o,"#PREFS_scrollwheelStep",P,!0),v(o,"#PREFS_showWorkingFilesSidebar",f),v(o,"#PREFS_showButtonForToolbar",g),v(o,"#PREFS_useIconsOfCustomWork",h),v(o,"#PREFS_autoHideTheTabmenu",p),v(o,"#PREFS_hoverSidebar",k),v(o,"#PREFS_tooltip",m),v(o,"#PREFS_scrollwheel",S),u.save())})}var r=brackets.getModule("widgets/Dialogs"),n=Mustache,s=brackets.getModule("strings"),a=brackets.getModule("command/Menus"),c=a.getMenu(a.AppMenuBar.NAVIGATE_MENU),i=brackets.getModule("command/CommandManager"),l=brackets.getModule("command/Commands"),d=brackets.getModule("preferences/PreferencesManager"),u=d.getExtensionPrefs("custom.work"),f="showWorkingFilesSidebar",g="showButtonForToolbar",h="useIconsOfCustomWork",p="autoHideTheTabmenu",k="hover.sidebar",m="tooltip",S="scrollwheel",P="scrollwheel.step",b="cw-version-in-localStorage",w=511,F=localStorage.getItem(b),E=require("text!./preferences.html"),M=n.render(E,s);R("Custom Work Preferences","PreferencesforCustomWorkforBrackets",I,a.AFTER,l.NAVIGATE_PREV_DOC_LIST_ORDER),(!F||w>parseInt(F,10))&&(localStorage.setItem(b,w),I())});`

**Comment by DH3ALEJANDRO** [comment]
update to version 5.1.2. fix bug
