### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by TiberiuLazar21** [DH3ALEJANDRO/custom-work-for-brackets#59]
I updated Brackets to version 1.7 and the Custom Work extension to the last version and now it displays like that. 
![brackets error](https://cloud.githubusercontent.com/assets/17326215/16178431/2c91c996-3650-11e6-9ded-7b4899ed9059.jpg)
 
So all icons disappeared and the menu in the left, on the top of the folder tree, it disappeared too.
I tried to reinstall both, the extension and the program, but the same problem. Any idea?

**Comment by DH3ALEJANDRO** [comment]
<i>brackets version?</i>
this is true > `"custom.work.useIconsOfCustomWork": true`

**Comment by TiberiuLazar21** [comment]
1.7

**Comment by TiberiuLazar21** [comment]
where i change that function and how i acces that console or what is it? I'm not so advanced. Thx

**Comment by TiberiuLazar21** [comment]
my problem is that the top bar with tabs doesn't look like the one from the extension pictures

**Comment by TiberiuLazar21** [comment]
and another problem that i found it now is that: the tab menu display only the type file extension
![brackets problem](https://cloud.githubusercontent.com/assets/17326215/16193045/88354174-36f5-11e6-9391-0795c83aa0c5.png)

**Comment by CHALLENGER22** [comment]
Same here error after update.. using 1.6 so rollback to previous version which works fine.

**Comment by TiberiuLazar21** [comment]
in 1.6 i got the same error, first i updated the extension and after the brackets

**Comment by DH3ALEJANDRO** [comment]
update

**Comment by TiberiuLazar21** [comment]
Thx
