### ISSUE TITLE
Conflicts with "Extensions Toolbar Reposition"

### ISSUE THREAD

**Issue by Coldwine** [DH3ALEJANDRO/custom-work-for-brackets#6]
You get a warning that both extensions are possibly modifying the same area and "Extensions Toolbar Reposition" gets disabled. Is this fixable at all or do we have to decide which of those to use?

**Comment by DH3ALEJANDRO** [comment]
is a extension conflict, you must use only one.
I'm going to get an upgrade, do not worry

**Comment by DH3ALEJANDRO** [comment]
update addon and change `brackets.json` `"custom.work.showButtonForToolbar": false`
