### ISSUE TITLE
New update messes with my editted styles

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#61]
How can i replace my editted style for this, i set custom colors. I see the css name and content is changed

**Comment by DH3ALEJANDRO** [comment]
open Console of Brackets and enter:
> `brackets.test.CommandManager.execute(brackets.test.Commands.FILE_OPEN, {
        fullPath: brackets.test.FileSystem.getFileForPath(brackets.test.ExtensionLoader.getUserExtensionPath()+"/custom-work-for-brackets/sys/simple.css").fullPath,
        paneId: brackets.test.MainViewManager.getActivePaneId()
})`
use "beautify" to make the code readable.
Now add your code :+1:

**Comment by DH3ALEJANDRO** [comment]
Please share your style file
