### ISSUE TITLE
Doesn´t Worf

### ISSUE THREAD

**Issue by waldos13** [DH3ALEJANDRO/custom-work-for-brackets#62]
Hey i have a problem i installl your plugin, but it doesn´t work, what can i do? i have the latest version of brackets it also works with de latest version of brackets de 1.7? Please help i love this plugin i have already use it before but now it doesn´t work.

**Comment by DH3ALEJANDRO** [comment]
yes 1.7.... :worried:  please screenshot

**Comment by DH3ALEJANDRO** [comment]
Please verify now
