### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by sanalpanicker** [DH3ALEJANDRO/custom-work-for-brackets#63]
I loved your plugin, it made my work so easy. I was excited seeing your new update, but so disappointed after I installed it.Please revert back your updates

**Comment by sanalpanicker** [comment]
I can no longer see the file icons, so file listing on the left side,my whole font and size of workspace got affected

**Comment by DH3ALEJANDRO** [comment]
:worried:  please screenshot

**Comment by sanalpanicker** [comment]
i removed the plugin, I cant go back to see the issues. :(

**Comment by sanalpanicker** [comment]
i think, i got it.During the installation it asked me if I want to enable the file panel and other options, i just skipped it.Where do i go back to enable it?

**Comment by DH3ALEJANDRO** [comment]
open Console of Brackets and enter:
> `brackets.test.CommandManager.execute("PreferencesforCustomWorkforBrackets")`
