### ISSUE TITLE
No tabs at all in 5.1.3 version

### ISSUE THREAD

**Issue by michaelkutuzov** [DH3ALEJANDRO/custom-work-for-brackets#64]
Good afternoon!
I have a problem: extension doesn't display  tabs  after last update.
![khhjj_croper_ru](https://cloud.githubusercontent.com/assets/20220032/16479384/961eee6a-3ea8-11e6-9bdc-9bf69e3e8995.png)

Here is my preferences for Custom Work
![kqkdf_croper_ru](https://cloud.githubusercontent.com/assets/20220032/16479529/a633853a-3ea9-11e6-9097-1f64e260f027.png)

**Comment by eroak** [comment]
Same issue for me

**Comment by DH3ALEJANDRO** [comment]
please screenshot of console

**Comment by michaelkutuzov** [comment]
![sx3qk_croper_ru](https://cloud.githubusercontent.com/assets/20220032/16495283/70644c9a-3ef5-11e6-81a6-a63823dd3597.png)
![ulrnw_croper_ru](https://cloud.githubusercontent.com/assets/20220032/16495282/70645a0a-3ef5-11e6-9edc-15473a394dba.png)
![0ln8o_croper_ru](https://cloud.githubusercontent.com/assets/20220032/16495284/706491d2-3ef5-11e6-953a-a31a01f8382b.png)

**Comment by DH3ALEJANDRO** [comment]
open Console and enter:
> `brackets.app.showOSFolder(brackets.test.ExtensionLoader.getUserExtensionPath()+"/custom-work-for-brackets/sys/tabbar.html")`

rename this file by: `tabBar.html`

comment :walking:

**Comment by michaelkutuzov** [comment]
All right! Thank you very much!
