### ISSUE TITLE
Turn off multiple buttons

### ISSUE THREAD

**Issue by inamoth** [DH3ALEJANDRO/custom-work-for-brackets#65]
![s__22437890](https://cloud.githubusercontent.com/assets/48197/16486997/04a45000-3f03-11e6-974f-ebb370ea1371.jpg)

Because there is a button , I can not see the file name.
Please add the option to turn off the button.

**Comment by DH3ALEJANDRO** [comment]
next version..... :+1:

**Comment by inamoth** [comment]
I made ​​sure that can be turned off in version 5.1.4.
Great Thanks!!
