### ISSUE TITLE
Horizontal Scroll Problem

### ISSUE THREAD

**Issue by juice** [DH3ALEJANDRO/custom-work-for-brackets#66]
If the Tab Bar is holding many Tabs and the Horizontal Scrolling starts, the snap in place at the end is not working properly.

Scrolling to the last Tab triggers the Tabs to jump around between the last two Tabs. The last Tab is also not completely visible and sits behind the Tab menu button.

I use Brackets 1.7 (on OS X El Capitan) and Custom Work 5.1.4. It started with the rewrite.
![gvqfkj9 - imgur](https://user-images.githubusercontent.com/4977825/43552624-d3b2946e-95b0-11e8-9270-c10db06301d9.gif)

**Comment by DH3ALEJANDRO** [comment]
<i>I apologize for the delay</i>
I did not find the problem, tested in mac.
Please more info... I tried on several obviously Capitan :worried:

**Comment by juice** [comment]
The Problem is still present. Sierra, Brackets 1.8 and Custom Work 5.1.5.

Maybe is it a Magic Mouse thing, to many scroll events in a short time.

**Comment by DH3ALEJANDRO** [comment]
Please, another gif...

**Comment by areknow** [comment]
Same issue for me. New macbook pro w/ touchbar. Brackets 1.9
![3](https://cloud.githubusercontent.com/assets/6361609/26233179/95ed2126-3c29-11e7-8f31-393995395b06.gif)

**Comment by DH3ALEJANDRO** [comment]
Update @juice @areknow

**Comment by areknow** [comment]
Unfortunately I'm still seeing the same issue with your newest update! 
![jun-13-2017 12-55-00](https://user-images.githubusercontent.com/6361609/27096731-a565bf92-5037-11e7-827a-de57f118bea4.gif)
Thank you

**Comment by DH3ALEJANDRO** [comment]
Check if this option is false `"custom.work.scrollwheel": false`

>Brackets Menu > Debug / Open Preferences File

**Comment by areknow** [comment]
@DH3ALEJANDRO I have that option set to `true`

**Comment by DH3ALEJANDRO** [comment]
@areknow  `true` is for scrolling, `false` is for adapting

**Comment by areknow** [comment]
@DH3ALEJANDRO yep I understand that, when I have it set to true for scrolling, I get the issue mentioned above :)

**Comment by DH3ALEJANDRO** [comment]
please answer if the latest version solves the problem

**Comment by areknow** [comment]
Sorry I switched to visual studio code a while back. Thank you for your help!
