### ISSUE TITLE
Scroll tabs on W7

### ISSUE THREAD

**Issue by Marco105** [DH3ALEJANDRO/custom-work-for-brackets#67]
Hello, I really love this extension !
On W7 I can't have scrolling tabs with mouse wheel, that's so bad for me.
Popup menu automatical deseapear when focus lost option:
Could this append on click on the main window?

An other things is that Minimap surrouned the popup menu...
This issue could be resolved on the minimap css z-index: 5 (maxi)

BTW

**Comment by DH3ALEJANDRO** [comment]
I not found the problem, please screenshot

**Comment by Marco105** [comment]
Yes that work fine when the bar is full of tabs.
Is possible to add some mouse wheel change tab or roll-up at next previous tab? e.g. Ctrl+MMB...

**Comment by DH3ALEJANDRO** [comment]
great idea! :octocat:

**Comment by DH3ALEJANDRO** [comment]
Please Update 😀

**Comment by Marco105** [comment]
Superb, lot of changes, all works very fine now ! Thank's for it !
