### ISSUE TITLE
Can not close second pane

### ISSUE THREAD

**Issue by monirulalom** [DH3ALEJANDRO/custom-work-for-brackets#68]
If I move a file to second pane using down key , there is no option for closing the pane , this should be fixed.

**Comment by DH3ALEJANDRO** [comment]
I not found the problem, please screenshot

**Comment by monirulalom** [comment]
Without plugin , I see a close button https://i.lithi.io/gzn5.png , don't see the close button after activating plugin https://i.lithi.io/WrxJ.png

**Comment by DH3ALEJANDRO** [comment]
This plugin tries to replace all that bar
> perhaps you want something like this?
![brackets](https://cloud.githubusercontent.com/assets/4977825/16569065/8b017da2-41f7-11e6-9830-79580c3f976d.png)

**Comment by monirulalom** [comment]
Better if you can add a close button beside show tabs menu.

**Comment by DH3ALEJANDRO** [comment]
<i>within tabs menu there is a button identical</i>
for close individual file or all files of focus pane?
