### ISSUE TITLE
How To Change Setting After Install

### ISSUE THREAD

**Issue by aliwsd** [DH3ALEJANDRO/custom-work-for-brackets#69]
Hi,
I Got a problem in File Icons After I Updated To New Version:
![problem](https://cloud.githubusercontent.com/assets/13856958/17050799/2dee12ee-500a-11e6-888f-7bda3b4816ff.jpg)
How Can I Change Setting And Remove Icons From Custom Work?

**Comment by DH3ALEJANDRO** [comment]
In Console of Brackets enter:
>`var pref = brackets.test.PreferencesManager.getExtensionPrefs("custom.work");
preferences.set("useIconsOfCustomWork", false);
preferences.save();
`
