### ISSUE TITLE
Tab Bar displayed as red, files not opening in new tabs and other

### ISSUE THREAD

**Issue by ItzMuffin** [DH3ALEJANDRO/custom-work-for-brackets#7]
Hi, i opened a new project and the extension was broken all over the place. The tab bar is red, files don't open in new tab, the settings icon is missing when in single view and the dropdown "explorer" doesn't even show the current open file, just a white arrow.

![schermata 2015-03-18 alle 15 45 12](https://cloud.githubusercontent.com/assets/7722619/6711348/bbe86fb6-cd86-11e4-9463-398eaa5bf2ae.png)

**Comment by RixzZ** [comment]
Same here.
![screenshot at 22-36-53](https://cloud.githubusercontent.com/assets/1339272/6719995/4ee412ec-cdbf-11e4-82b7-ce7c8cf8044c.png)

**Comment by DH3ALEJANDRO** [comment]
you have to start editing to add it to the bar otherwise is just a visualization of the file.

**Comment by DH3ALEJANDRO** [comment]
solved in version 5.0.0
