### ISSUE TITLE
Wrecks current Brackets install, have to delete and reinstall and set-up. DON'T INSTALL!

### ISSUE THREAD

**Issue by sipersoft** [DH3ALEJANDRO/custom-work-for-brackets#70]
This is the _third_ time I've installed Brackets, got all the extensions I wanted and set them up, and then everything goes to hell when I install your Tabs extension. Even after removing it, the issues persist.

Does your code modify native Brackets code? Seriously, you need to put a disclaimer that people's stuff is going to get wrecked if they use this.

Running: Brackets - Release 1.7 build 1.7.0-16898 (release b0a363b71) 
System: Mac OS X El Capitan

Below is a screenshot of the console output. I have spent hours trying to fix this already, and do not have the time to go any further.

![Console output](https://cloud.githubusercontent.com/assets/6828884/17096102/fdaf94ec-5214-11e6-8adf-2968e4e3f8ee.png)

Like I said, the issues only start once your extension is installed, but it does NOT go away after disabling or removing it. This extension needs to be taken down immediately. People's time is valuable, they don't need to waste it having to reinstall and set-up their coding environment.

**Comment by DH3ALEJANDRO** [comment]
errors are caused by another extension, I'm using on multiple computers and there is no such problem, anyway I try to find a solution...

**Comment by sipersoft** [comment]
I installed Brackets 1.6 (same Mac OS X El Capitan system), and there were no issues with the tabs. It's something to do with the new release. I'd have kept the earlier version, but it is lacking some features that I switched editors specifically for.

To be fair to you, *every* tabs extension causes the same issues. But yours is prettier than the others, so I spent more time with yours, trying to make it work.

It's incredible how many extensions have not been updated for the current build. Almost all of them were giving warnings - at the minimum - but many were throwing fatal exceptions. All of the other ones were easy enough to modify, but yours will either have to be a) a major overhaul of your code, or b) a patch made for Bracket. I imagine the former is the more likely.

I might make a new issue for Brackets.io, since it's every tabs extension that is causing this issue. What *really* needs to be done is a build of Brackets needs to be put together that gets rid of the "Working Files" bit, and replaces it with proper stacked tabs like every other editor.

Wish I could help you put together a new tabs extension, but no time at the present.

**Comment by DH3ALEJANDRO** [comment]
:+1:  great review, I am delighted.
try to remove this extension:
>`brackets.app.showOSFolder(brackets.getModule("extensibility/ExtensionManager").extensions.NavigationAndHistory.installInfo.path);`

then install brackets 1.7 and then see if the problem continues

<i>I also modified other extensions to solve compatibility.</i>

**Comment by sipersoft** [comment]
I'm going to have to skip trying this out for a while. By the time I install it, get all the extensions I want, organize their settings, modify the majority of them to not throw warnings or errors, modify multiple files to get the hotkeys set properly, etc, etc... It takes the better part of a work day to fight with everything. I'll let you know if I ever get the time for it, but for the next couple months I'm slammed.

Good luck though.

**Comment by DH3ALEJANDRO** [comment]
:+1:
