### ISSUE TITLE
All Icons are monochrome with new release (5.1.4)

### ISSUE THREAD

**Issue by pmullot** [DH3ALEJANDRO/custom-work-for-brackets#71]
Just installed the 5.1.4 release, my Bracket version is still 1.6.0. I'm working on Linux Mint 64bits.
I guess it's something about config but don't how to fix it.

![brackets](https://cloud.githubusercontent.com/assets/75703/17241825/35ce0dd8-5574-11e6-9cbc-8087b65e0102.png)

How can I get them back to colour?

**Comment by DH3ALEJANDRO** [comment]
In Console of Brackets enter:

var preferences = brackets.test.PreferencesManager.getExtensionPrefs("custom.work"); preferences.set("grayScaleIcons", false); preferences.save();
