### ISSUE TITLE
Control+Z No funciona

### ISSUE THREAD

**Issue by tejadong** [DH3ALEJANDRO/custom-work-for-brackets#72]
Cuando tienes la vista dividida en modo vertical y mueves ficheros entre esas vista, parece ser que cuando modificas código y presionas el control+s para guardar, cuando quieres deshacer los cambios con control+z no funciona. En cambio, en la otra vista que tengo a la izquierda si funciona. Para que me vuelva a funcionar tengo que desinstalar y volver a instalar el plugin.

Gracias.

**Comment by DH3ALEJANDRO** [comment]
Please, try fix. guarda tus extensiones y tu archivo `brackets.json` luego desinstala la aplicación; vuelve a instalar y devuelve tus extensiones y tu fichero de config `brackets.json`. con esto estaria solucionado, comenta 😃

**Comment by tejadong** [comment]
Yo lo que hice fue desinstalar el plugin y lo volví a instalar pero parece ser que cuando quiere vuelve a pasar este error... ¿a qué se debe?

**Comment by DH3ALEJANDRO** [comment]
pues nunca me ocurrio, asi que la unica solucion es esta: https://github.com/adobe/brackets/wiki/Cache-Folder#resetting-cache--preferences
prueba si funciona
(que version de SO y brackets estas usando?)

**Comment by tejadong** [comment]
Hice lo que te dije y aun no me ha vuelto a pasar, si vuelve a pasarme hare lo que me recomiendas.

Tengo Windows 10, la versión de Brackets es la última actual.
