### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by felipeblan** [DH3ALEJANDRO/custom-work-for-brackets#73]
Icons are not showing next to the files neither on the tabs.
![image](https://cloud.githubusercontent.com/assets/4297415/20217141/76fbfb1a-a7ec-11e6-8731-6de89d84a147.png)

**Comment by DH3ALEJANDRO** [comment]
Please SO version and brackets version

**Comment by felipeblan** [comment]
OS: Linux Mint 17.3 64 bit
Brackets Version: Release 1.8 experimental build 1.8.0-17108

**Comment by 92k1** [comment]
![bug2](https://cloud.githubusercontent.com/assets/7395833/20218282/c0543242-a85e-11e6-8c84-ec9f88283871.png)

OS:  ubuntu 16.04
brackets version:  Release 1.8 experimental build 1.8.0-17108 
The same problem here.

**Comment by DH3ALEJANDRO** [comment]
Please download these files and replace in Custom Work files.
[CW-Fonts.zip](https://github.com/DH3ALEJANDRO/custom-work-for-brackets/files/585987/CW-Fonts.zip)

`Menu Brackets/Help/Show Extensions Folder`
and find `user/custom-work-for-brackets/sys/evr/icomoon.woff2`
Here replace `icomoon.woff2` by `icomoon.woff` or `icomoon.ttf`
and edit `user/custom-work-for-brackets/sys/icons.min.css`
>>`@font-face{font-family:icomoon;src:url(evr/icomoon.woff2) format('woff2')}`
by @font-face{font-family:icomoon;src:url(evr/icomoon.woff) format('woff')}
or @font-face{font-family:icomoon;src:url(evr/icomoon.ttf) format('truetype')}
try it and comment...

**Comment by felipeblan** [comment]
Working now. I used @font-face{font-family:icomoon;src:url(evr/icomoon.ttf) format('truetype')}. Thanks.

**Comment by 92k1** [comment]
It works.Thanks.

**Comment by systemroot** [comment]
another probl
preview and plugins button lost their place
![](http://image.prntscr.com/image/69953130a1ca4d65ab69153409a97d6d.png)

Ubuntu 14.04, Brackets Release 1.8 experimental build 1.8.0-17108, default black theme.

**Comment by DH3ALEJANDRO** [comment]
Is a option; disabled in Custom Work preferences. Menu Tabs of Tab Bar

**Comment by systemroot** [comment]
you did this like this? i was thinking it's a problem! it's good for me i like it.
because on default place that can eat some screen and i can't see full code as i want
