### ISSUE TITLE
The status bar does not show completely

### ISSUE THREAD

**Issue by 92jz** [DH3ALEJANDRO/custom-work-for-brackets#74]
before disable custom-work:
![11 18](https://cloud.githubusercontent.com/assets/7395833/20396960/f19f0de0-ad22-11e6-8963-73ca98622a3d.png)

after disable custom-work:
![11 18 1](https://cloud.githubusercontent.com/assets/7395833/20397205/df457048-ad23-11e6-941c-a2a1549bc070.png)

OS: ubuntu 16.04
bracket's version: Release 1.8 experimental build 1.8.0-17108

**Comment by DH3ALEJANDRO** [comment]
What is the theme you are using?

**Comment by 92jz** [comment]
Solarized Dark, if I use  the default, there is the same issue.

**Comment by DH3ALEJANDRO** [comment]
I apologize for the delay, I was offline.
Please Update.
