### ISSUE TITLE
Open document list

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#75]
I did a update today and i preferred the open documents in a list on the left side. Is there a option to put it back like that?

**Comment by DH3ALEJANDRO** [comment]
The answer is no, it cannot be anymore

**Comment by schroef** [comment]
Why not make the menu reside on the left at the regular list and be able to fold it. The list on the right side is just awkward, its not fitting in the design GUI very well. i also see some glitches when you swap the side bar from right to bottom left. The menu list also floats behind this panel sometimes

**Comment by schroef** [comment]
Its when you first set it to the bottom and then uncheck it. See screengrab
<img width="494" alt="screen shot 2016-11-25 at 1 07 10 pm" src="https://cloud.githubusercontent.com/assets/6923008/20631953/2b7f025c-b310-11e6-8651-fe26313391cd.png">

**Comment by DH3ALEJANDRO** [comment]
Great Idea!. 🎉

**Comment by schroef** [comment]
I had a new update and from the images i see the menu looks different. Though on install and reload i still see same menu as above or are the images on the main page older?

**Comment by DH3ALEJANDRO** [comment]
The page is old.

**Comment by schroef** [comment]
I do like that menu bar more than this current one if im honest, ps what is the new update? i dont see any difference in the menu, i thought it was able to fold now. I still see that error with it going behind the main toolbar on the right. But i see other plugins show issues here as well. Sometimes the toolbar shifts to the right leaving a black hole to the right of it. It happens when i move the toolbar to the left and back.

see screengrab
<img width="327" alt="screen shot 2016-12-01 at 4 16 27 pm" src="https://cloud.githubusercontent.com/assets/6923008/20810801/97779a20-b7e1-11e6-9436-1f3b72515fd4.png">

**Comment by schroef** [comment]
PS i just noticed that bookmark function, is it possible to name these? or add this function?

**Comment by DH3ALEJANDRO** [comment]
please try remove "No Distraction" addon.
I'm working in this addon.
What's with the bookmark?

**Comment by schroef** [comment]
I dont have "No Distractions" addon, if i understand/rad well. Its under main settings see "other" in preferences. Its unchecked and is under view menu, its a bracket system thing. Using or not using this has no effect on that black gab i showed earlier.

About the bookmarks, i see i small icon and see a list of bookmarks, they all show linenumber. I thought perhaps naming them would be nice, but would be a lot of coding i guess. They only acts as a single link, not each bookmark per document is clickable.

**Comment by DH3ALEJANDRO** [comment]
current version 5.1.8
enable option ShowWorkingListViewonLeftSidebar > brackets preferences or Custom Work preferences

**Comment by schroef** [comment]
nice, thanks for updating it.
