### ISSUE TITLE
Glitches in Brackets's UI with only Custom Working extension enabled.

### ISSUE THREAD

**Issue by BobbyBabes** [DH3ALEJANDRO/custom-work-for-brackets#77]
With the Brackets default theme active, and Custom Working being the only enabled extension, Bracket's editor windows are positioned to the right of the menu (instead of below the menu). With the menu taking up space from top to bottom.
Also, at the bottom of the 2 editor windows, some whitespace is added.

Have you any idea what might cause this?

**OS:** Arch Linux
**OS version:** Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
**Brackets version:**  Release 1.8 experimental build 1.8.0-0
The page of the package : https://aur.archlinux.org/packages/brackets/

![brackets-default-theme-with-only-custom-working-extension-enabled-errors-with-menu-and-bottom-of-editor-windows](https://cloud.githubusercontent.com/assets/22870070/21265833/88b45532-c3a3-11e6-8e5d-295c0791fcb3.png)

**Comment by DH3ALEJANDRO** [comment]
<i>I apologize for the delay, I was offline.</i>
Please comment if the problem persists

**Comment by BobbyBabes** [comment]
This is the internet. No problems.
I'm not using Brackets anymore. Uninstalled long ago.
Visual Studio Code is my main editor now, and somewhat Atom.

**Comment by DH3ALEJANDRO** [comment]
👍
