### ISSUE TITLE
Remove Pane Arrows from Tabs?

### ISSUE THREAD

**Issue by Key7i** [DH3ALEJANDRO/custom-work-for-brackets#78]
Is it possible to remove pane arrows from tabs? I don't use pane views on my small screen.. Both top and right pane view arrows are huge problem in tabs hover. I mistakenly click on it all the time and then i have to get that tab back and remove second pane view. It would be a great help if i can remove both pane view options.

Thanks for this extension.

**Comment by DH3ALEJANDRO** [comment]
Solved 😄 
update and disable option `splitButton` > brackets preferences or Custom Work preferences

**Comment by Key7i** [comment]
Thanks Alejandro.. :+1: Its working great now. :)
