### ISSUE TITLE
Click outside submenu hides menu

### ISSUE THREAD

**Issue by techlantis** [DH3ALEJANDRO/custom-work-for-brackets#79]
Typical usage goes like this, and its frustrating as hell.

-I have two vertical split panes
-I run out of space and cannot find a tab I just opened
-I toggle the side menu to see a list of items, find file in question great
-Click outside the submenu expecting it to close, it does not, repeat this several times as its counter intuitive to all other popup windows...
-See an X icon, Oh that must be to close this sub menu that wont go away...

LOSE ALL FILES that were loaded 👎 

Can we have that sub menu close when you click out side it, or move that X away from the universal position to close a window.

Thanks.

**Comment by DH3ALEJANDRO** [comment]
solved 😄 
update and enable option `autoHideTheTabmenu` > brackets preferences or Custom Work preferences

**Comment by techlantis** [comment]
Wohoo! Thanks, my life is forever improved🥇  😄
