### ISSUE TITLE
The tabs would be "responsive"

### ISSUE THREAD

**Issue by davidbarredo** [DH3ALEJANDRO/custom-work-for-brackets#8]
When I have several files open and the filenames are too long, the tabs disappears on the right side and they are only accesible by the menu.

If I select one of the "invisibles" tabs I can work with the file, but I don't see the current tab in the tab bar.

A posible solution would be to make posible navigate between tabs.

Another solution could be make it responsive like the tabs in Sublime:![Sublime screenshot](https://shoffing.files.wordpress.com/2013/04/sublime-text.png)
In the screenshot if we make the window editor smaller the tabs will be smaller too, but all visibles.

**Comment by DH3ALEJANDRO** [comment]
possibly it was resolved in version 5.0.0, In the next version you will have the option to stack tabs
