### ISSUE TITLE
Toolbar disapear in 1.9

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#82]
I had autoupdate on and i got a reload warning today. After bracket reloaded i see the toolbar is missing on the right. It only show now when i move it to the left panel.

this is OSX 10.11.6 in Brackts 1.9. What i do find weird, when i just looked here in Github i dont see any updates recently. Last update was couple weeks ago and we discussed some items if i recall it correct.
<img width="1440" alt="screen shot 2017-03-27 at 12 50 33 am" src="https://cloud.githubusercontent.com/assets/6923008/24341477/fa39e306-1287-11e7-811b-e0142c5e9034.png">

**Comment by schroef** [comment]
Sorry, didnt check if no stractions was on, somehow i had turned it on.

this one is solved than

**Comment by DH3ALEJANDRO** [comment]
Did you solve the problem?

**Comment by schroef** [comment]
Yes its solved. PS was there an update? i dont see it in you data but Brackets gave me your plugin screen, so i think it got updated
