### ISSUE TITLE
Change shortcut keys for existing actions

### ISSUE THREAD

**Issue by krompir2** [DH3ALEJANDRO/custom-work-for-brackets#84]
Lovely extension you've created. I was wondering if it is possible to change the shortcut keys and how?

Regards, Mitt

**Comment by DH3ALEJANDRO** [comment]
https://github.com/adobe/brackets/wiki/User-Key-Bindings

`"Custom Work"` Command:
Menu ListView: `"customworkKeyIdListView"`

**Comment by AlexBlandin** [comment]
What are the actual keybindings though? Surely this is a good thing to add to the readme at the very least, as the keybindings are currently said to be "default" but doesn't say how to change

**Comment by DH3ALEJANDRO** [comment]
The only "Custom Work" shortcut is as follows > `"customworkKeyIdListView"`

The default shortcuts are from the editor itself.

The other commands are in the direction below
https://github.com/adobe/brackets/blob/master/src/command/Commands.js

1. NAVIGATE_NEXT_DOC &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= "navigate.nextDoc"; 
2. NAVIGATE_PREV_DOC&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= "navigate.prevDoc";
3. NAVIGATE_NEXT_DOC_LIST_ORDER&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= "navigate.nextDocListOrder"; 
4. NAVIGATE_PREV_DOC_LIST_ORDER&nbsp;&nbsp;&nbsp;&nbsp; = "navigate.prevDocListOrder";
5. VIEW_HIDE_SIDEBAR&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;= "view.toggleSidebar";

and 
https://github.com/adobe/brackets/blob/master/src/extensions/default/NavigationAndHistory/keyboard.json

1. "recent-files.show"
2. "recent-files.next"
3. "recent-files.prev"
