### ISSUE TITLE
How do I access the pop-up settings menu?

### ISSUE THREAD

**Issue by bobziroll** [DH3ALEJANDRO/custom-work-for-brackets#86]
I saw it the first time I installed, but now I don't know how to access it. It isn't in any of the menus (Edit, Navigate, etc.). I might be glancing over it, but I only ever got the pop-up the first time I installed and can't seem to get it back, even after uninstalling and re-installing.

Brackets info - Release 1.9 build 1.9.0-17312 (release 189f6d39a) 
Custom Work - v. 5.1.8

**Comment by DH3ALEJANDRO** [comment]
![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)
