### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by krunal222** [DH3ALEJANDRO/custom-work-for-brackets#87]
'Custom Work' brackets plugins
Avril Alejandro
5.1.8	

This plugin very helpful but sometime's does not work for this plugin. Refresh my brackets window 2-4 time so hide this plugin.

**Comment by DH3ALEJANDRO** [comment]
Please can be more descriptive, is the first report

**Comment by mrttahd** [comment]
I have the same problem. I'm using Brackets 1.9 build 1.9.0-17312 ( latest version on http://brackets.io)
Please see the attached image below.

**Comment by DH3ALEJANDRO** [comment]
@mrttahd Explain the problem

**Comment by mrttahd** [comment]
@DH3ALEJANDRO Thank you for reply. My problem's I can't see multi tabs. I tried to open about 20 files but I can't see "buttons show/hide with tabs of active documents on the top of the editor"

**Comment by DH3ALEJANDRO** [comment]
@mrttahd, @krunal222 and.....

temporary solution
----

In the bracket console run the following code

`var filePath = brackets.app.getApplicationSupportDirectory()+"/extensions/user/custom-work-for-brackets/sys/simple.min.css";
brackets.test.CommandManager.execute(brackets.test.Commands.FILE_OPEN, {fullPath: filePath});`

At the end of the open file paste the following

    .main-view.cw-nonscroll .cw-ul {
        width: 100%;
    }



Save and close it

*I will try to solve some errors. The update will be soon*

*offer my apologies for the inconvenience* Avril Alejandro

**Comment by DH3ALEJANDRO** [comment]
Update

**Comment by Rockjaw01** [comment]
I just installed your plugin and I'm having the same problem the other two had. I'm using Brackets 1.9 (the most current from the Brackets site) and closed Brackets and opened back up and I have not tabs at the top.  I've looked through every menu option many times and don't see any place to enable it so any idea what could be wrong?  I've uninstalled and reinstalled several times with no luck.

**Comment by Rockjaw01** [comment]
Just did a ctrl + tab and now the tabs are showing up when they didn't before.  I'll take it.  Thanks for creating this!
