### ISSUE TITLE
Possible incompatibility with 'WD Minimap' extension

### ISSUE THREAD

**Issue by AntonioNav** [DH3ALEJANDRO/custom-work-for-brackets#9]
I had installed 'WD Minimap' and then I installed your plugin. It's works well, but when I press the right button for 'hide toolbar' the 'minimap' dissapear. When I try to press again the button for 'show toolbar', toolbar is showed, but the minimap still not working. The button for 'show worklist' doesn't work too.

**Comment by DH3ALEJANDRO** [comment]
"WD Minimap" not well developed, I will find a solution to this, I also hope that the developer "WD Minimap" improve its extension.

**Comment by DH3ALEJANDRO** [comment]
I can not find solution for this extension :unamused:
