### ISSUE TITLE
{ SOLVED } On updates and installment settings screen show

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#91]
How can i see that startup screen which shows when you first install or upgrade the plugin, i find it much better to read than the regular preferences menu?

**Comment by schroef** [comment]
Nevermind got it :)

**Comment by DH3ALEJANDRO** [comment]
![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)
*There are many people who cannot access this menu ...*
