### ISSUE TITLE
Short cuts - show tab menu doesnt do anythonig

### ISSUE THREAD

**Issue by schroef** [DH3ALEJANDRO/custom-work-for-brackets#92]
Br 1.9.0-17312
OSC 10.11.6

I was reading the settings screen and noted some short cuts. I tried using show tabs view cmd + shift + T but nothing happens

Toggle side bar doesnt work, is this different than standard cmd + shift + h?

**Comment by DH3ALEJANDRO** [comment]
Wow, it's a mistake on my part, it should be  "cmd + shift + V".

[The next is Brackets shortcut](https://github.com/adobe/brackets/wiki/Brackets-Shortcuts)
