### ISSUE TITLE
Getting weird panel layout issue

### ISSUE THREAD

**Issue by michaelmlin** [DH3ALEJANDRO/custom-work-for-brackets#95]
Hi,

I am getting an empty panel in the right-side of Brackets when using your cool extension.

Please help.

Thanks,

Mike

![screen shot 2017-07-20 at 1 45 50 pm](https://user-images.githubusercontent.com/285976/28438096-c586723a-6d51-11e7-8080-d688a4a2a96b.png)

**Comment by judeOtenyo** [comment]
me too...

**Comment by DH3ALEJANDRO** [comment]
@michaelmlin @judeOtenyo 
<strike>*Is caused by another extension*</strike>.
Please go to this link #88

**Comment by DH3ALEJANDRO** [comment]
Duplicate of #88

**Comment by DH3ALEJANDRO** [comment]
Duplicate of #88
