### ISSUE TITLE
setting toggle

### ISSUE THREAD

**Issue by q403ge** [DH3ALEJANDRO/custom-work-for-brackets#97]
Ive recently stumbled across this extension, and loving it.  One thing that ive been looking to do with it is bring back the settings panel that comes up with the initial install. I dont see any options available to toggle this window. 

I also use another extension that allows the panel/"distractions" to show on mouseover, but if the toolbar is moved to the left it sticks out like a sore thumb. ill include the other extension, should there be some code tweaking for them to play nicely together... 
https://github.com/holmar/brackets-no-distractions-advanced

![custom work issue](https://user-images.githubusercontent.com/29168473/29574837-997a0d20-8717-11e7-8f1d-10c0f2f2693b.jpg)

**Comment by DH3ALEJANDRO** [comment]
😃 
Show settings
![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)

**Leave me some days I will try to integrate it into those extensions**

😸

**Comment by DH3ALEJANDRO** [comment]
*fixed, please update the Custom Work*
