### ISSUE TITLE
How can i change Custom Work settings and make the plugins bar go back to its original position?

### ISSUE THREAD

**Issue by vanessaddiniz** [DH3ALEJANDRO/custom-work-for-brackets#98]
I really wanna do this but i don't know how. Now the plugins appear in the left sidebar. I wanna make them go back to the default position.

**Comment by DH3ALEJANDRO** [comment]
Open the editor console and enter

var PreferencesManager = brackets.getModule("preferences/PreferencesManager"),
    prefs = PreferencesManager.getExtensionPrefs("custom.work"),
    toolbar = prefs.set("moveToolbarToSidebar", false);


*for more*
https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences

![howtoopen](https://cloud.githubusercontent.com/assets/4977825/26496187/17e6bda0-41ec-11e7-8cb0-0b9c7299a88f.png)
